services:
    offline:
        container_name: Dev.Coasters.Offline
        image: coasters/backend
        build:
            context: ../../
            dockerfile: Dockerfile
            target: dev
        tty: true # helps to preserve colors in the console
        volumes:
            - ../../:/app # mount the project root directory, backend hot reload
            - /app/node_modules # prevent node_modules from being overwritten
        environment:
            - NODE_ENV=development
            - NODE_NAME=Coasters.Offline
            - NODE_BASE_URL=/offline
            - PORT=3050
            - LOGS_DIRECTORY=/app/data/dev/offline/logs/
            - COASTERS_DATABASE_PATH=/app/data/dev/offline/coasters.db.json
            - OFFLINE_MODE=true
        ports:
            - 9229:9229 # nodejs debugger
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:3050/health"]
            interval: 5s
            timeout: 10s
            retries: 5
        labels:
            - traefik.enable=true
            - traefik.http.routers.dev-offline-node.rule=PathPrefix(`/offline`)
            - traefik.http.middlewares.dev-offline-node-strip.stripprefix.prefixes=/offline
            - traefik.http.routers.dev-offline-node.middlewares=dev-offline-node-strip
            - traefik.http.services.dev-offline-node.loadbalancer.server.port=3050
        networks:
            - coasters-backend-services

networks:
    coasters-backend-services:
        name: Shared.Coasters.Backend.Services
        driver: bridge
