
services:
    dev-swagger:
        image: swaggerapi/swagger-ui
        container_name: Dev.Coasters.Swagger
        environment:
            - URLS=[{"name":"Dev Offline Node","url":"/offline/api/"},{"name":"Dev Cluster Node-1","url":"/cluster/node-1/api/"},{"name":"Dev Cluster Node-2","url":"/cluster/node-2/api/"}]
            - DEEP_LINKING=true
        labels:
            - traefik.enable=true
            - traefik.http.routers.dev-swagger.rule=PathPrefix(`/`)
            - traefik.http.services.dev-swagger.loadbalancer.server.port=8080
        networks:
            - coasters-backend-services

networks:
    coasters-backend-services:
        name: Shared.Coasters.Backend.Services
        driver: bridge
