services:
    prod-offline:
        container_name: Prod.Coasters.Offline
        image: coasters/backend
        build:
            context: ../../
            dockerfile: Dockerfile
            target: prod
        tty: true # helps to preserve colors in the console
        environment:
            - NODE_ENV=production
            - NODE_NAME=Coasters.Offline
            - NODE_BASE_URL=/offline/api
            - PORT=3050
            - LOGS_DIRECTORY=/app/data/prod/offline/logs/
            - COASTERS_DATABASE_PATH=/app/data/prod/offline/coasters.db.json
            - OFFLINE_MODE=true
        volumes:
            - ../../data/:/app/data # mount the data directory
        ports:
            - 9232:9229 # nodejs debugger
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:3050/health"]
            interval: 5s
            timeout: 10s
            retries: 5
        labels:
            - traefik.enable=true
            - traefik.http.routers.prod-offline-node.entrypoints=prod-env
            - traefik.http.routers.prod-offline-node.rule=PathPrefix(`/offline/api`)
            - traefik.http.middlewares.prod-offline-node-strip.stripprefix.prefixes=/offline/api
            - traefik.http.routers.prod-offline-node.middlewares=prod-offline-node-strip
            - traefik.http.services.prod-offline-node.loadbalancer.server.port=3050
        networks:
            - coasters-backend-prod-services

networks:
    coasters-backend-prod-services:
        name: Prod.Coasters.Backend.Services
        driver: bridge
