services:
    prod-proxy:
        container_name: Prod.Coasters.Proxy
        image: traefik:2.9.6
        ports:
            - 3051:3051
        networks:
            - coasters-backend-prod-services
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ../traefik-config.yml:/etc/traefik/traefik.yml:ro

networks:
    coasters-backend-prod-services:
        name: Prod.Coasters.Backend.Services
        driver: bridge
