
services:
    prod-swagger:
        image: swaggerapi/swagger-ui
        container_name: Prod.Coasters.Swagger
        environment:
            - URLS=[{"name":"Prod Offline Node","url":"/offline/api/"},{"name":"Prod Cluster Node-1","url":"/cluster/node-1/api/"},{"name":"Prod Cluster Node-2","url":"/cluster/node-2/api/"}]
            - DEEP_LINKING=true
        labels:
            - traefik.enable=true
            - traefik.http.routers.prod-swagger.rule=PathPrefix(`/`)
            - traefik.http.services.prod-swagger.loadbalancer.server.port=8080
        networks:
            - coasters-backend-services

networks:
    coasters-backend-services:
        name: Shared.Coasters.Backend.Services
        driver: bridge
